name: Build fouda store application

on:
  workflow_dispatch:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-front-and-back-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Extract Maven project version
        run: |
          echo "VERSION=$(mvn --file fouda-store-backend/pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> "$GITHUB_ENV"


      - name:  Build back-end
        run: mvn -B package --file fouda-store-backend/pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fouda-store-backend/
          push: true
          tags: ziedayadi/fouda-store-backend:${{ env.VERSION }}
          build-args: |
            BUILD_VERSION=${{ env.VERSION }}

      - name:  Prepare Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name:  NPM Install
        run: npm install ./fouda-store-frontend/

      - name:  NPM Build
        run: npm run build --prefix ./fouda-store-frontend/

      - name: Build and push frontend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fouda-store-frontend/
          push: true
          tags: ziedayadi/fouda-store-frontend:${{ env.VERSION }}
           
     
