name: Migrate flyway

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Envirement to migrate'
        required: false
        type: choice
        options:
          - INT
          - REC
          - PROD


jobs:
  migrate-flyway:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{secrets[format('{0}_DB_URL', inputs.enviroment)] }}
      DB_USER: ${{secrets[format('{0}_DB_USER', inputs.enviroment)] }}
      DB_PASSWORD: ${{secrets[format('{0}_DB_PASSWORD', inputs.enviroment)] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: execute flyway
        run: mvn flyway:migrate -f fouda-store-backend/pom.xml -Dflyway.url=${{env.DB_URL}} -Dflyway.user=${{env.DB_USER}} -Dflyway.password=${{env.DB_PASSWORD}} -Dflyway.schemas=postgres