name: Migrate flyway

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Envirement to migrate'
        required: false
        type: choice
        options:
          - INT
          - REC
          - PROD

      version:
        description: 'Version to install in DB'
        required: false
        type: string


jobs:
  migrate-flyway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: checkout version to migrate
        id: checkout_version
        if: ${{ inputs.version != null }}
        run: git checkout ${{ inputs.version }}

      - name: execute flyway
        run: mvn flyway:migrate -f fouda-store-backend/pom.xml -Dflyway.url=${{secrets.REC_DB_URL}} -Dflyway.user=${{secrets.REC_DB_USER}} -Dflyway.password=${{secrets.REC_DB_PASSWORD}} -Dflyway.schemas=postgres  