name: Release fouda store application

on:
#  push:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        type: string
      next-dev-version:
        description: 'Next development version'
        required: true
        type: string


jobs:
  release-front-and-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform release ${{ inputs.release-version }}
        uses: qcastel/github-actions-maven-release@v1.12.41
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@sema4.com"
          release-branch-name: main
          maven-project-folder: "fouda-store-backend/"
          maven-development-version-number: ${{ inputs.next-dev-version }}
          maven-release-version-number: ${{ inputs.release-version }}
          maven-args: "-Dmaven.deploy.skip=true"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push backend docker image ${{ inputs.release-version }}
        uses: docker/build-push-action@v5
        with:
          context: ./fouda-store-backend/
          push: true
          tags: ziedayadi/fouda-store-backend:${{ inputs.release-version }}
          build-args: |
            BUILD_VERSION=${{ inputs.release-version }}

      - name: NPM Install
        run: npm install ./fouda-store-frontend/

      - name: NPM Build
        run: npm run build --prefix ./fouda-store-frontend/

      - name: Build and push frontend docker image ${{ inputs.release-version }}
        uses: docker/build-push-action@v5
        with:
          context: ./fouda-store-frontend/
          push: true
          tags: ziedayadi/fouda-store-frontend:${{ inputs.release-version }}