name: Release fouda store application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        type: string
      next-dev-version:
        description: 'Next development version'
        required: true
        type: string


jobs:
  release-front-and-back:
    runs-on: ubuntu-latest

    steps:
      - name: Release back
        uses: qcastel/github-actions-maven-release@v1.12.41
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@sema4.com"
          maven-project-folder: "fouda-store-backend/"
          maven-development-version-number: ${{ inputs.next-dev-version }}
          maven-release-version-number: ${{ release-version }}