name: Release fouda store application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        type: string
      next-dev-version:
        description: 'Next development version'
        required: true
        type: string


jobs:
  build-and-push-front-and-back-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name:  Release backend
        run: mvn -f fouda-store-backend/pom.xml release:perform \
          --batch-mode \
          -Dtag=fouda-store-${{inputs.release-version}} \
          -DreleaseVersion=${{inputs.release-version}} \
          -DdevelopmentVersion=${{inputs.next-dev-version}}