name: Release fouda store application

on:
#  push:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        type: string
      next-dev-version:
        description: 'Next development version'
        required: true
        type: string


jobs:
  release-front-and-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform release
        uses: qcastel/github-actions-maven-release@v1.12.41
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@sema4.com"
          release-branch-name: main
          maven-project-folder: "fouda-store-backend/"
          maven-development-version-number: ${{ inputs.next-dev-version }}
          maven-release-version-number: ${{ inputs.release-version }}
          maven-args: "-Dmaven.deploy.skip=true"

      - name: Create docker image (checkou tag)
        run: git checkout ${{ inputs.release-version }}

      - name: Create docker image (maven build tag)
        run: mvn -B package --file fouda-store-backend/pom.xml