name: Release fouda store application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        type: string
      next-dev-version:
        description: 'Next development version'
        required: true
        type: string


jobs:
  release-front-and-back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Prepare git
        run: git config --global user.name "github actions usename" && git config --global user.email "github@sema4conseil.fr"

      - name: Release clean
        run: mvn -f fouda-store-backend/pom.xml release:clean
      - name: Release prepare
        run: mvn release:prepare --batch-mode -DreleaseVersion=${{inputs.release-version}} -DdevelopmentVersion=${{inputs.next-dev-version}} --file fouda-store-backend/pom.xml
      - name: Release perform
        run: mvn release:perform --batch-mode -DreleaseVersion=${{inputs.release-version}} -DdevelopmentVersion=${{inputs.next-dev-version}} --file fouda-store-backend/pom.xml
 